import ScheduleActivity from '../models/ScheduleActivity.js';
import MatchResult from '../models/MatchResult.js';
import { extractEvents } from './extractionService.js';
const stop=new Set(['the','and','for','area','work','today','started','completed','continued']); const canon=x=>({erection:'erect',erecting:'erect',installation:'install',installed:'install',fabrication:'fabricate',fabricated:'fabricate',alignment:'align',aligned:'align',flushing:'flush',cleaning:'clean',spools:'spool',valves:'valve',cables:'cable',panels:'panel'}[x]||x);
const toks=s=>new Set((s||'').toLowerCase().replace(/[^a-z0-9- ]/g,' ').split(/\s+/).filter(x=>x.length>2&&!stop.has(x)).map(canon));
function sim(a,b){const A=toks(a),B=toks(b);let inter=0;A.forEach(x=>B.has(x)&&inter++);return A.size||B.size?100*(2*inter/(A.size+B.size)):0}
function score(e,a){let activity=sim(e.activityDescription,a.activityName), discipline=e.discipline&&a.discipline&&e.discipline.toLowerCase()===a.discipline.toLowerCase()?100:50, location=e.location&&a.location&&e.location.toLowerCase()===a.location.toLowerCase()?100:50, identifier=0;const ids=(e.rawText.match(/(?:line|equipment|unit|spool)\s*[a-z0-9-]+/ig)||[]).join(' ');identifier=sim(ids,a.activityName+' '+a.activityId);const nums=[...(e.rawText||'').matchAll(/\b(?:line|spool|equipment|unit)\s*([a-z0-9-]+)/ig)].map(x=>x[1].toLowerCase());const aid=(a.activityName+' '+a.activityId).toLowerCase();if(nums.some(n=>aid.includes(n)))identifier=Math.max(identifier,100);const overall=Math.round(activity*.5+discipline*.15+location*.15+identifier*.2);return {overall,activity,discipline,location,identifier}}
export async function processText({projectId,text,userId,documentId}){const acts=await ScheduleActivity.find({projectId,wbsLevel:{$in:['L5','L6']}});const events=extractEvents(text);const out=[];for(const e of events){let best=null;for(const a of acts){const s=score(e,a);if(!best||s.overall>best.s.overall)best={a,s}}const status=!best||best.s.overall<75?'UNMATCHED':'PENDING';const m=await MatchResult.create({projectId,progressEventId:null,scheduleActivityId:best?.a?._id,confidenceScore:best?.s.overall||0,matchingMethod:'hybrid: keyword + fuzzy/context',matchingFactors:best?.s||{},status});out.push({event:e,match:m,activity:best?.a||null})}return out}
export {score};
