import {Router} from 'express';import multer from 'multer';import path from 'path';import fs from 'fs';import {protect,authorize} from '../middleware/auth.js';import * as auth from '../controllers/authController.js';import * as projects from '../controllers/projectController.js';import * as schedule from '../controllers/scheduleController.js';import * as progress from '../controllers/progressController.js';import * as matching from '../controllers/matchingController.js';import * as agent from '../controllers/timeAgentController.js';import * as analytics from '../controllers/analyticsController.js';
const r=Router();const dir=process.env.UPLOAD_DIR||'uploads';fs.mkdirSync(dir,{recursive:true});const upload=multer({dest:dir,limits:{fileSize:10*1024*1024},fileFilter:(req,f,cb)=>{const ext=path.extname(f.originalname).toLowerCase();cb(null,['.csv','.xlsx','.xls','.txt'].includes(ext))}});
r.post('/auth/register',auth.register);r.post('/auth/login',auth.login);r.get('/auth/me',protect,auth.me);
r.use(protect);r.get('/projects',projects.list);r.post('/projects',projects.create);r.get('/projects/:id',projects.get);r.put('/projects/:id',projects.update);r.delete('/projects/:id',authorize('Admin','Project Manager'),projects.remove);
r.post('/schedule/upload',upload.single('file'),schedule.upload);r.get('/schedule/:projectId',schedule.list);r.delete('/schedule/:id',schedule.remove);
r.post('/progress/upload',upload.single('file'),progress.upload);r.get('/progress/:projectId',progress.list);
r.post('/matching/process',matching.process);r.get('/matching/:projectId',matching.list);r.post('/matching/:id/approve',authorize('Admin','Project Manager','Planner'),matching.approve);r.post('/matching/:id/reject',authorize('Admin','Project Manager','Planner'),matching.reject);r.put('/matching/:id',authorize('Admin','Project Manager','Planner'),matching.change);
r.post('/time-agent/message',agent.message);r.post('/time-agent/confirm',agent.confirm);
r.get('/analytics/:projectId',analytics.analytics);r.get('/project-memory/:projectId',analytics.memory);r.get('/audit/:projectId',analytics.audit);r.get('/users',authorize('Admin'),analytics.users);r.get('/progress/:projectId/live',analytics.progress);export default r;
