services:
  - type: web
    name: infratrack-ai-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: LLM_API_KEY
        sync: false
