import 'dotenv/config';import express from 'express';import cors from 'cors';import path from 'path';import {connectDB} from './config/db.js';import routes from './routes/index.js';import {bootstrapDemoData} from './bootstrap.js';
const app=express();
const allowed=process.env.CLIENT_URL?process.env.CLIENT_URL.split(',').map(x=>x.trim()):true;
app.use(cors({origin:allowed}));
app.use(express.json({limit:'2mb'}));
app.use('/uploads',express.static(path.resolve(process.env.UPLOAD_DIR||'uploads')));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'InfraTrack AI',authentication:'disabled-local'}));
app.use('/api',routes);
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({message:err.code==='LIMIT_FILE_SIZE'?'File too large':err.message||'Request failed'})});
connectDB().then(async()=>{await bootstrapDemoData();app.listen(process.env.PORT||5000,()=>console.log(`API running on http://localhost:${process.env.PORT||5000}`))}).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
