import {useEffect,useState} from 'react';import {UploadCloud,Check, X, Send, Search} from 'lucide-react';import api from '../services/api';import {getProject} from '../utils/project';import {Page} from './Projects';import {Loading,Empty} from '../components/UI';
export function Ingestion(){
 const pid=getProject();const [file,setFile]=useState(null),[source,setSource]=useState('DAILY_REPORT'),[text,setText]=useState(''),[result,setResult]=useState(null),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 async function upload(e){e.preventDefault();setErr('');setBusy(true);try{if(text.trim()){const r=await api.post('/matching/process',{projectId:pid,text});setResult({results:r.data})}else{const fd=new FormData();fd.append('file',file);fd.append('projectId',pid);fd.append('sourceType',source);const r=await api.post('/progress/upload',fd);setResult(r.data)}}catch(x){setErr(x.response?.data?.message||'Processing failed')}finally{setBusy(false)}}
 return <Page title="Data Ingestion" sub="Upload field evidence, extract the event, review the AI match, then approve or reject it">
 <div className="grid lg:grid-cols-2 gap-5">
  <div className="card p-5"><h2 className="font-bold mb-4">Upload field report</h2><form onSubmit={upload} className="space-y-4">
   <div><label className="label">Source type</label><select className="input" value={source} onChange={e=>setSource(e.target.value)}>{['DAILY_REPORT','DISCIPLINE_REPORT','SITE_DIARY','OTHER'].map(x=><option key={x}>{x}</option>)}</select></div>
   <div><label className="label">CSV / XLSX / XLS / TXT</label><input className="input" type="file" accept=".csv,.xlsx,.xls,.txt" onChange={e=>setFile(e.target.files[0])}/></div>
   <div className="text-center text-xs text-slate-400">— OR paste free-text —</div>
   <textarea className="input" rows="7" placeholder={"04 September 2026\nPiping work continued in Area A.\nLine 24 spool erection started today."} value={text} onChange={e=>setText(e.target.value)}/>
   <button disabled={!pid||(!file&&!text.trim())||busy} className="btn-primary w-full"><UploadCloud size={17}/>{busy?'Processing...':'Extract & Match'}</button>{err&&<p className="text-sm text-red-600">{err}</p>}
  </form></div>
  <div className="card p-5"><h2 className="font-bold mb-4">AI review</h2>{result?<Result data={result} onChange={setResult}/>:<Empty text="Upload a report to extract events and create a pending match"/>}</div>
 </div></Page>
}
function Result({data,onChange}){
 const rs=data.results||[];
 async function action(id,type,i){try{const r=await api.post(`/matching/${id}/${type}`);const next=[...rs];next[i]={...next[i],match:r.data.match||r.data};onChange({...data,results:next})}catch(e){alert(e.response?.data?.message||'Action failed')}}
 return <div className="space-y-4">{rs.map((r,i)=>{const m=r.match||{};const a=m.scheduleActivityId||r.activity||{};return <div className="border rounded-xl p-4" key={m._id||i}>
  <div className="text-xs uppercase text-slate-500 mb-2">Extracted event</div><div className="font-semibold">{r.event?.activityDescription}</div>
  <div className="grid grid-cols-2 gap-2 text-sm mt-3"><span>Event: <b>{r.event?.eventType}</b></span><span>Date: <b>{String(r.event?.eventDate||'').slice(0,10)}</b></span><span>Discipline: <b>{r.event?.discipline||'—'}</b></span><span>Location: <b>{r.event?.location||'—'}</b></span></div>
  <div className="mt-3 p-3 bg-blue-50 rounded-lg"><div className="text-xs text-blue-700">Suggested L5/L6 match</div><div className="font-bold">{a.activityId||'No suitable activity'}</div><div>{a.activityName||'Unmatched'}</div><div className="text-sm mt-1">Confidence: <b>{m.confidenceScore||0}%</b></div></div>
  {m.status==='PENDING'&&m._id&&<div className="flex gap-2 mt-4"><button onClick={()=>action(m._id,'approve',i)} className="btn-primary flex-1"><Check size={16}/> Approve & update progress</button><button onClick={()=>action(m._id,'reject',i)} className="btn-secondary"><X size={16}/> Reject</button></div>}
  {m.status==='APPROVED'&&<div className="mt-4 p-3 rounded-lg bg-emerald-50 text-emerald-700 font-semibold">Approved — actual progress updated in the database.</div>}
  {m.status==='REJECTED'&&<div className="mt-4 p-3 rounded-lg bg-slate-100 text-slate-700 font-semibold">Rejected — schedule progress was not changed.</div>}
  {m.status==='UNMATCHED'&&<div className="mt-4 p-3 rounded-lg bg-amber-50 text-amber-700 font-semibold">Unmatched — no progress was changed. Review it in AI Matching.</div>}
 </div>})}{!rs.length&&<Empty text="No events detected in this report"/>}</div>
}
export function Matching(){const pid=getProject();const [rows,setRows]=useState([]),[busy,setBusy]=useState(true),[q,setQ]=useState('');async function load(){if(!pid){setBusy(false);return}setRows((await api.get('/matching/'+pid)).data);setBusy(false)}useEffect(()=>{load()},[]);async function action(id,type){await api.post(`/matching/${id}/${type}`);load()}const shown=rows.filter(m=>JSON.stringify(m).toLowerCase().includes(q.toLowerCase()));return <Page title="AI Matching" sub="Human-in-the-loop validation for field-to-schedule reconciliation">{busy?<Loading/>:!pid?<Empty text="Select a project first"/>:<><div className="card p-4 mb-4"><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={18}/><input className="input pl-9" placeholder="Search matches..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="space-y-3">{shown.map(m=><div className="card p-5" key={m._id}><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex-1"><div className="text-sm text-slate-500">{m.progressEventId?.rawText}</div><div className="mt-2 font-bold">{m.progressEventId?.activityDescription}</div><div className="text-sm mt-1">→ {m.scheduleActivityId?.activityId} · {m.scheduleActivityId?.activityName}</div><div className="text-xs text-slate-500 mt-2">Method: {m.matchingMethod}</div></div><div className="text-center"><div className="text-2xl font-bold text-blue-700">{m.confidenceScore}%</div><div className="text-xs text-slate-500">confidence</div></div><div className="flex gap-2">{m.status==='PENDING'&&<><button onClick={()=>action(m._id,'approve')} className="btn-primary"><Check size={16}/> Approve</button><button onClick={()=>action(m._id,'reject')} className="btn-secondary"><X size={16}/> Reject</button></>}{m.status!=='PENDING'&&<span className="px-3 py-2 rounded-lg bg-slate-100 text-sm font-semibold">{m.status}</span>}</div></div></div>)}{!shown.length&&<Empty text="No matching records yet"/>}</div></>}</Page>}
export function Unmatched(){const pid=getProject();const [rows,setRows]=useState([]);useEffect(()=>{if(pid)api.get('/matching/'+pid).then(r=>setRows(r.data.filter(x=>x.status==='UNMATCHED')))},[]);return <Page title="Unmatched Activities" sub="Records with no sufficiently confident L5/L6 match are preserved for action"><div className="card overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Field activity</th><th className="p-3 text-left">Source event</th><th className="p-3 text-left">Confidence</th><th className="p-3 text-left">Reason</th><th className="p-3 text-left">Action</th></tr></thead><tbody>{rows.map(x=><tr className="border-t" key={x._id}><td className="p-3">{x.progressEventId?.activityDescription}</td><td className="p-3">{x.progressEventId?.rawText}</td><td className="p-3">{x.confidenceScore}%</td><td className="p-3">No match met the 75% threshold</td><td className="p-3"><button className="btn-secondary">Find Match</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No unmatched activities"/>}</div></Page>}
export function Progress(){const pid=getProject();const [rows,setRows]=useState([]);useEffect(()=>{if(pid)api.get('/progress/'+pid+'/live').then(r=>setRows(r.data))},[]);return <Page title="Progress" sub="Actual execution reconciled against planned dates"><div className="card overflow-auto scrollbar"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{['ID','Activity','Discipline','Planned Start','Actual Start','Planned End','Actual End','Variance','Progress','Status'].map(x=><th className="p-3 text-left whitespace-nowrap" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(a=>{const v=a.actualEnd&&a.plannedEnd?Math.round((new Date(a.actualEnd)-new Date(a.plannedEnd))/86400000):null;return <tr className="border-t" key={a._id}><td className="p-3 font-semibold">{a.activityId}</td><td className="p-3 min-w-52">{a.activityName}</td><td className="p-3">{a.discipline}</td><td className="p-3">{a.plannedStart?.slice(0,10)}</td><td className="p-3">{a.actualStart?.slice(0,10)||'—'}</td><td className="p-3">{a.plannedEnd?.slice(0,10)}</td><td className="p-3">{a.actualEnd?.slice(0,10)||'—'}</td><td className="p-3 font-semibold">{v==null?'—':`${v>0?'+':''}${v}d`}</td><td className="p-3">{a.progress||0}%</td><td className="p-3">{a.status}</td></tr>})}</tbody></table>{!rows.length&&<Empty text="No L5/L6 activities in this project"/>}</div></Page>}
